---
abstract: 'Object approach at reading explain analyze output'
author:
  - 'hubert depesz lubaczewski <depesz@depesz.com>'
build_requires:
  Test::Deep: 0
  Test::Exception: 0
  Test::More: 0
  autodie: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pg-Explain
provides:
  Pg::Explain:
    file: lib/Pg/Explain.pm
    version: 0.68
  Pg::Explain::From:
    file: lib/Pg/Explain/From.pm
    version: 0.68
  Pg::Explain::FromJSON:
    file: lib/Pg/Explain/FromJSON.pm
    version: 0.68
  Pg::Explain::FromText:
    file: lib/Pg/Explain/FromText.pm
    version: 0.68
  Pg::Explain::FromXML:
    file: lib/Pg/Explain/FromXML.pm
    version: 0.68
  Pg::Explain::FromYAML:
    file: lib/Pg/Explain/FromYAML.pm
    version: 0.68
  Pg::Explain::Node:
    file: lib/Pg/Explain/Node.pm
    version: 0.68
  Pg::Explain::StringAnonymizer:
    file: lib/Pg/Explain/StringAnonymizer.pm
    version: 0.68
requires:
  Clone: 0
  Digest::SHA1: 0
  HOP::Lexer: 0
  JSON: 0
  XML::Simple: 0
  YAML: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.68
